alpha: 0.3
item_emb_reg_weight: 0.0
item_emb_reg_type: 'l2'
item_emb_reg_temp: 0.3
item_emb_reg_learnable_temp: False
temp: 0.1
lambda: 10
learnable_align_temp: False

c: 9
fusion_type: "gate"
valid_metric: NDCG@20
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.3




# general
gpu_id: 0
use_gpu: True
seed: 42
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False

# dataset
load_col:
    inter: [user_id, item_id, rating, timestamp]
    item: ['item_id','title','sales_rank','price','brand','categories','sales_type']
MAX_ITEM_LIST_LENGTH: 50
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

# Filtering
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# Model
n_layers: 2
n_heads: 2
hidden_size: 256
attribute_hidden_size: [256,256]
inner_size: 256
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
selected_features: ['categories','brand']
pooling_mode: 'sum'
loss_type: 'CE'
weight_sharing: 'not'




# Pretrained Semantic ID Embedding
use_pretrained_emb: True
pretrained_emb_path: '/root/blockdata/diffandletter/LETTER/data/Sports_and_Outdoors/Sports_and_Outdoors.ordered.npy'
pretrained_emb_dim: 768
freeze_pretrained_emb: False

# training settings
epochs: 200
train_batch_size: 256
learner: adam
learning_rate: 0.0001
eval_step: 1
stopping_step: 20
clip_grad_norm: ~
weight_decay: 0.0
neg_sampling:

# evaluation settings
eval_args:
  split: { 'LS': 'valid_and_test' }
  group_by: user
  order: TO
  mode: full

repeatable: True
metrics: ["Recall","NDCG"]
topk: [10,20]
valid_metric_bigger: True
eval_batch_size: 1024
loss_decimal_place: 4
metric_decimal_place: 4
align: True
enable_frequency_layer: True